[package]
name = "dec_4_b"
version = "0.1.0"
authors = ["yarocruz <yarocruz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
nom = "7.1.0"